version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Azerty@123
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1